/* eslint-disable */

// noinspection JSUnusedGlobalSymbols

type RouteTreeNodeMetadata = {
  id: string;
  path: string;
  getParentRoute: () => unknown;
};

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ComposeRouteImport } from './routes/compose'
import { Route as ControlPlaneRouteImport } from './routes/control-plane'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as RegistryRouteImport } from './routes/registry'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as SystemsRouteImport } from './routes/systems'
import { Route as SystemsAssuranceRouteImport } from './routes/systems/assurance'
import { Route as SystemsBusinessRouteImport } from './routes/systems/business'
import { Route as SystemsIntelligenceRouteImport } from './routes/systems/intelligence'
import { Route as SystemsVerticalOsRouteImport } from './routes/systems/vertical-os'
import { Route as SystemsVoiceRouteImport } from './routes/systems/voice'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as unknown as Parameters<typeof IndexRouteImport.update>[0] & RouteTreeNodeMetadata)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as unknown as Parameters<typeof AuditRouteImport.update>[0] & RouteTreeNodeMetadata)
const ComposeRoute = ComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => rootRouteImport,
} as unknown as Parameters<typeof ComposeRouteImport.update>[0] & RouteTreeNodeMetadata)
const ControlPlaneRoute = ControlPlaneRouteImport.update({
  id: '/control-plane',
  path: '/control-plane',
  getParentRoute: () => rootRouteImport,
} as unknown as Parameters<typeof ControlPlaneRouteImport.update>[0] & RouteTreeNodeMetadata)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as unknown as Parameters<typeof InsightsRouteImport.update>[0] & RouteTreeNodeMetadata)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as unknown as Parameters<typeof PartnersRouteImport.update>[0] & RouteTreeNodeMetadata)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as unknown as Parameters<typeof PlatformRouteImport.update>[0] & RouteTreeNodeMetadata)
const RegistryRoute = RegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => rootRouteImport,
} as unknown as Parameters<typeof RegistryRouteImport.update>[0] & RouteTreeNodeMetadata)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as unknown as Parameters<typeof ResearchRouteImport.update>[0] & RouteTreeNodeMetadata)
const SystemsRoute = SystemsRouteImport.update({
  id: '/systems',
  path: '/systems',
  getParentRoute: () => rootRouteImport,
} as unknown as Parameters<typeof SystemsRouteImport.update>[0] & RouteTreeNodeMetadata)
const SystemsAssuranceRoute = SystemsAssuranceRouteImport.update({
  id: '/assurance',
  path: '/assurance',
  getParentRoute: () => SystemsRoute,
} as unknown as Parameters<typeof SystemsAssuranceRouteImport.update>[0] & RouteTreeNodeMetadata)
const SystemsBusinessRoute = SystemsBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => SystemsRoute,
} as unknown as Parameters<typeof SystemsBusinessRouteImport.update>[0] & RouteTreeNodeMetadata)
const SystemsIntelligenceRoute = SystemsIntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => SystemsRoute,
} as unknown as Parameters<typeof SystemsIntelligenceRouteImport.update>[0] & RouteTreeNodeMetadata)
const SystemsVerticalOsRoute = SystemsVerticalOsRouteImport.update({
  id: '/vertical-os',
  path: '/vertical-os',
  getParentRoute: () => SystemsRoute,
} as unknown as Parameters<typeof SystemsVerticalOsRouteImport.update>[0] & RouteTreeNodeMetadata)
const SystemsVoiceRoute = SystemsVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => SystemsRoute,
} as unknown as Parameters<typeof SystemsVoiceRouteImport.update>[0] & RouteTreeNodeMetadata)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/compose': typeof ComposeRoute
  '/control-plane': typeof ControlPlaneRoute
  '/insights': typeof InsightsRoute
  '/partners': typeof PartnersRoute
  '/platform': typeof PlatformRoute
  '/registry': typeof RegistryRoute
  '/research': typeof ResearchRoute
  '/systems': typeof SystemsRouteWithChildren
  '/systems/assurance': typeof SystemsAssuranceRoute
  '/systems/business': typeof SystemsBusinessRoute
  '/systems/intelligence': typeof SystemsIntelligenceRoute
  '/systems/vertical-os': typeof SystemsVerticalOsRoute
  '/systems/voice': typeof SystemsVoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/compose': typeof ComposeRoute
  '/control-plane': typeof ControlPlaneRoute
  '/insights': typeof InsightsRoute
  '/partners': typeof PartnersRoute
  '/platform': typeof PlatformRoute
  '/registry': typeof RegistryRoute
  '/research': typeof ResearchRoute
  '/systems': typeof SystemsRouteWithChildren
  '/systems/assurance': typeof SystemsAssuranceRoute
  '/systems/business': typeof SystemsBusinessRoute
  '/systems/intelligence': typeof SystemsIntelligenceRoute
  '/systems/vertical-os': typeof SystemsVerticalOsRoute
  '/systems/voice': typeof SystemsVoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/compose': typeof ComposeRoute
  '/control-plane': typeof ControlPlaneRoute
  '/insights': typeof InsightsRoute
  '/partners': typeof PartnersRoute
  '/platform': typeof PlatformRoute
  '/registry': typeof RegistryRoute
  '/research': typeof ResearchRoute
  '/systems': typeof SystemsRouteWithChildren
  '/systems/assurance': typeof SystemsAssuranceRoute
  '/systems/business': typeof SystemsBusinessRoute
  '/systems/intelligence': typeof SystemsIntelligenceRoute
  '/systems/vertical-os': typeof SystemsVerticalOsRoute
  '/systems/voice': typeof SystemsVoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/compose'
    | '/control-plane'
    | '/insights'
    | '/partners'
    | '/platform'
    | '/registry'
    | '/research'
    | '/systems'
    | '/systems/assurance'
    | '/systems/business'
    | '/systems/intelligence'
    | '/systems/vertical-os'
    | '/systems/voice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/compose'
    | '/control-plane'
    | '/insights'
    | '/partners'
    | '/platform'
    | '/registry'
    | '/research'
    | '/systems'
    | '/systems/assurance'
    | '/systems/business'
    | '/systems/intelligence'
    | '/systems/vertical-os'
    | '/systems/voice'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/compose'
    | '/control-plane'
    | '/insights'
    | '/partners'
    | '/platform'
    | '/registry'
    | '/research'
    | '/systems'
    | '/systems/assurance'
    | '/systems/business'
    | '/systems/intelligence'
    | '/systems/vertical-os'
    | '/systems/voice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  ComposeRoute: typeof ComposeRoute
  ControlPlaneRoute: typeof ControlPlaneRoute
  InsightsRoute: typeof InsightsRoute
  PartnersRoute: typeof PartnersRoute
  PlatformRoute: typeof PlatformRoute
  RegistryRoute: typeof RegistryRoute
  ResearchRoute: typeof ResearchRoute
  SystemsRoute: typeof SystemsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compose': {
      id: '/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof ComposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-plane': {
      id: '/control-plane'
      path: '/control-plane'
      fullPath: '/control-plane'
      preLoaderRoute: typeof ControlPlaneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry': {
      id: '/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems': {
      id: '/systems'
      path: '/systems'
      fullPath: '/systems'
      preLoaderRoute: typeof SystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems/assurance': {
      id: '/systems/assurance'
      path: '/assurance'
      fullPath: '/systems/assurance'
      preLoaderRoute: typeof SystemsAssuranceRouteImport
      parentRoute: typeof SystemsRoute
    }
    '/systems/business': {
      id: '/systems/business'
      path: '/business'
      fullPath: '/systems/business'
      preLoaderRoute: typeof SystemsBusinessRouteImport
      parentRoute: typeof SystemsRoute
    }
    '/systems/intelligence': {
      id: '/systems/intelligence'
      path: '/intelligence'
      fullPath: '/systems/intelligence'
      preLoaderRoute: typeof SystemsIntelligenceRouteImport
      parentRoute: typeof SystemsRoute
    }
    '/systems/vertical-os': {
      id: '/systems/vertical-os'
      path: '/vertical-os'
      fullPath: '/systems/vertical-os'
      preLoaderRoute: typeof SystemsVerticalOsRouteImport
      parentRoute: typeof SystemsRoute
    }
    '/systems/voice': {
      id: '/systems/voice'
      path: '/voice'
      fullPath: '/systems/voice'
      preLoaderRoute: typeof SystemsVoiceRouteImport
      parentRoute: typeof SystemsRoute
    }
  }
}

interface SystemsRouteChildren {
  SystemsAssuranceRoute: typeof SystemsAssuranceRoute
  SystemsBusinessRoute: typeof SystemsBusinessRoute
  SystemsIntelligenceRoute: typeof SystemsIntelligenceRoute
  SystemsVerticalOsRoute: typeof SystemsVerticalOsRoute
  SystemsVoiceRoute: typeof SystemsVoiceRoute
}

const SystemsRouteChildren: SystemsRouteChildren = {
  SystemsAssuranceRoute: SystemsAssuranceRoute,
  SystemsBusinessRoute: SystemsBusinessRoute,
  SystemsIntelligenceRoute: SystemsIntelligenceRoute,
  SystemsVerticalOsRoute: SystemsVerticalOsRoute,
  SystemsVoiceRoute: SystemsVoiceRoute,
}

const SystemsRouteWithChildren =
  SystemsRoute._addFileChildren(SystemsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  ComposeRoute: ComposeRoute,
  ControlPlaneRoute: ControlPlaneRoute,
  InsightsRoute: InsightsRoute,
  PartnersRoute: PartnersRoute,
  PlatformRoute: PlatformRoute,
  RegistryRoute: RegistryRoute,
  ResearchRoute: ResearchRoute,
  SystemsRoute: SystemsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
